# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20161012_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
