# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20161027_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_until',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='client.DeviceModel'),
        ),
    ]
