# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:48
from __future__ import unicode_literals

from django.db import migrations


def link_devices(apps, schema_editor):
    """
    link the new model ids with the old data.
    """
    DeviceModel = apps.get_model('client', 'DeviceModel')
    Device = apps.get_model('client', 'Device')
    for dev in Device.objects.all():
        mdl, created = DeviceModel.objects.get_or_create(name=dev.model)
        dev.model_link = mdl
        dev.save()


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20161117_1248'),
    ]

    operations = [
        migrations.RunPython(link_devices)
    ]
