# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_device_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='model_link',
            new_name='model',
        ),
    ]
