# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='diagnosis',
            field=models.TextField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='used_parts',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='storage.Part'),
        ),
    ]
