# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('ticket', '0003_remove_ticket_used_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('serial_number', models.CharField(blank=True, default='', max_length=30)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Part')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='parts',
            field=models.ManyToManyField(through='ticket.Charges', to='storage.Part'),
        ),
    ]
