# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20161019_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='actions',
            field=models.TextField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
