# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20161019_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='storage.Part'),
        ),
        migrations.AlterField(
            model_name='charges',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='ticket.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='parts',
            field=models.ManyToManyField(related_name='tickets', through='ticket.Charges', to='storage.Part'),
        ),
    ]
